google/GoogleDataTransport

.gitignore
GoogleDataTransport.podspec
GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
GoogleDataTransport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
GoogleDataTransport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.h
GoogleDataTransport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m
Package.swift

- validate that all events passed to GDT are actually sent to the server with no errors.
- fix SPM

More detailed and useful integration tests

---

GoogleDataTransport/GDTCCTLibrary/GDTCCTCompressionHelper.m

Fix for new clang vla error

---

Package.swift

For GDT 8.4.0 and Firebase 7.10.0

Update nanopb version for SPM

---

CHANGELOG.md

Apologies, realized I never updated the CHANGELOG for #18. I believe this is the only changelog update for 9.0

Update CHANGELOG.md for GDT 9.0

---

CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m

Fix https://github.com/firebase/firebase-ios-sdk/issues/8134

Fix Xcode 12.5 analyze errors

---

GoogleDataTransport.podspec

Proposing to publish main here as a 9.0.1 after a nightly test run with Firebase from SpecsStaging.

Update podspec for a 9.0.1 release

---

README.md

* `--skip-tests` for `pod trunk push`
* SpecsStaging cleanup detailed commands
* GitHub Release creation

More detail for Publish instructions

---

GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
GoogleDataTransport/GDTCORLibrary/GDTCORAssert.m
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

Fixes CI failures in #32 & #34.
#no-changelog

Apply clang-format version 12.0.1 style

---

.github/workflows/test_coverage.yml

Fix paths in test_coverage.yml

---

GoogleDataTransport/GDTCORLibrary/Internal/GDTCORLifecycle.h

Follow-up work from #44
#no-changelog

Remove `GDTCORLifecycle` conformance to `GDTCORApplicationDelegate`

---

GoogleDataTransport/GDTCCTTestApp/app.swift
GoogleDataTransport/GDTCCTTestApp/gdthelpers.swift
GoogleDataTransport/GDTCCTTestApp/globals.swift
GoogleDataTransport/GDTCCTTestApp/viewcontroller.swift
GoogleDataTransport/GDTCCTWatchOSTestApp/GDTCCTServiceExtension/NotificationService.swift
GoogleDataTransport/GDTCCTWatchOSTestApp/GDTCCTWatchOSCompanionTestAppExtension/InterfaceController.swift
GoogleDataTransport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/InterfaceController.swift
GoogleDataTransport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/gdthelpers.swift
GoogleDataTransport/GDTTestApp/EventCleanupPerfTest.swift
GoogleDataTransport/GDTTestApp/app.swift
GoogleDataTransport/GDTTestApp/globals.swift
GoogleDataTransport/GDTTestApp/viewcontroller.swift
GoogleDataTransport/GDTWatchOSTestApp/GDTWatchOSTestAppWatchKitExtension/InterfaceController.swift
Mintfile

Upgrade swift-format to match firebase-ios-sdk

---

.github/workflows/check.yml
GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.c
README.md

[Infra] Upgrade `clang-format` to `clang-format@14`

---

GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCOREventMetricsCounter.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage+Promises.m
GoogleDataTransport/GDTCORLibrary/GDTCORMetrics.m
GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
GoogleDataTransport/GDTCORLibrary/GDTCORMetricsMetadata.m
GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageSizeBytes.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCOREventMetricsCounter.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetrics.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetricsMetadata.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorageMetadata.h
GoogleDataTransport/GDTCORTests/Unit/GDTCORMetricsControllerTest.m

- Continued wiring up the metrics controller with storage and data model objects
- Filled in some documentation now that things are becoming more stable
- Implement metrics unit tests

[Metrics] Continue implementation of metrics controller

---

GoogleDataTransport.podspec
GoogleDataTransport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
GoogleDataTransport/GDTCCTTests/Unit/GDTCORMetrics+GDTCCTSupportTests.m
GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCCTTestRequestParser.h
GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCCTTestRequestParser.m
GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCORMetricsTestHelpers.h
GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCORMetricsTestHelpers.m
GoogleDataTransport/GDTCCTTests/Unit/Helpers/NSData+GDTCOREventDataObject.h
GoogleDataTransport/GDTCCTTests/Unit/Helpers/NSData+GDTCOREventDataObject.m
GoogleDataTransport/GDTCORLibrary/GDTCOREventMetricsCounter.m
GoogleDataTransport/GDTCORLibrary/GDTCORMetrics.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetrics.h
GoogleDataTransport/GDTCORTests/Unit/GDTCOREventMetricsCounterTest.m

- Direct followup to #70
1. Update integration tests for new metrics component
2. Resolve any outstanding todos
2. E2E tests

[Metrics] Add tests for `GDTCORMetric`'s `GDTCOREventDataObject` conformance

---

.github/workflows/datatransport.yml
.github/workflows/test_coverage.yml
GoogleDataTransport.podspec
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransport/GDTCCTLibrary/GDTCOREvent+GDTMetricsSupport.m
GoogleDataTransport/GDTCCTLibrary/GDTCORMetrics+GDTCCTSupport.m
GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTUploader.h
GoogleDataTransport/GDTCCTLibrary/Private/GDTCOREvent+GDTMetricsSupport.h
GoogleDataTransport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetricsController.h

- Added integration tests for the added metrics component
- The new tests mainly verify that metrics are added to a given target if the target supports metrics collection

[Metrics] Add integration tests for metrics component

---

.github/workflows/check.yml
.github/workflows/datatransport.yml
.github/workflows/spm.yml
.github/workflows/test_coverage.yml

The GDT equivalent of https://github.com/firebase/firebase-ios-sdk/pull/9498

[Infra] Add `cancel-in-progress` feature to GHA

---

Gemfile
Gemfile.lock
setup-scripts.sh

Following up on https://github.com/google/GoogleDataTransport/pull/82#discussion_r940784280
#no-changelog

[Infra] Remove `xcpretty` from `Gemfile` and `Gemfile.lock`

---

GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
GoogleDataTransport/GDTCORLibrary/GDTCOREndpoints.m
GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORTargets.h

[Infra] Improve docs and use google domain for testing URL

---

CHANGELOG.md
GoogleDataTransport.podspec

[Release] Bump spec to 9.2.1 and add CHANGELOG entry

---

.github/workflows/check.yml
README.md

[Infra] Upgrade to clang-format16

---

GoogleDataTransport.podspec

[Release] Bump 'GoogleDataTransport.podspec' version from '9.2.2' → '9.2.3'

---

GoogleDataTransport.podspec

Like https://github.com/firebase/firebase-ios-sdk/pull/9782 and https://github.com/google/GoogleUtilities/pull/121

[Infra] Update licensing version in podspec

---

CHANGELOG.md
GoogleDataTransport.podspec

Will merge after #108 merges, and then stage podspec for testing.

[Release] Update podspec and changelog for 9.3.0 release

---

GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m

Fixes https://github.com/firebase/firebase-ios-sdk/issues/9859.

Fix badfood crashes and add diagnostic

---

GoogleDataTransport.podspec
GoogleDataTransport/Resources/PrivacyInfo.xcprivacy
Package.swift

[GoogleDataTransport] Add privacy manifest for SPM / CocoaPods

---

CHANGELOG.md
GoogleDataTransport.podspec

[Release] Bump spec to 9.4.0 and add changelog entry

---

CHANGELOG.md
GoogleDataTransport.podspec
README.md

Fix #119
Fix https://github.com/firebase/firebase-ios-sdk/issues/12477

[CocoaPods] Prep for 9.4.1 patch release

---

.github/workflows/check.yml
GoogleDataTransport/GDTCORLibrary/GDTCORLogSourceMetrics.m

Style script does not always run and missed error in #125

[NFC] Fix check workflow and style file

---

CHANGELOG.md
GoogleDataTransport.podspec
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTTestApp/EventCleanupPerfTest.swift
GoogleDataTransport/GDTTestApp/viewcontroller.swift
Package.swift

Part of https://github.com/firebase/firebase-ios-sdk/issues/10187

[v10] Minimum platform updates

---

GoogleDataTransport.podspec

[Infra] Update GoogleDataTransport.podspec

---

GoogleDataTransport.podspec

Merged `main` into `release-10.0` in preparation for the 10.0 release.

[v10] Merge `main` into `release-10.0`
