- GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
- GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
- GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
- GoogleDataTransport/generate_project.sh
- b/171573251: respect Retry-After header
- fix background task completion
- don't remove events for all 5xx server responses, not only for 503
> Respect Retry-After header

- GoogleDataTransport.podspec
- GoogleDataTransport/CHANGELOG.md
- GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
- GoogleDataTransport/GDTCCTLibrary/GDTCOREvent+GDTCCTSupport.m
- GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTUploadOperation.h
- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage+Promises.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadCoordinatorTest.m
- Fix https://github.com/firebase/firebase-ios-sdk/issues/7771 (TSAN and undefined behavior diagnostics warnings)
- fix `-[GDTCORUploadCoordinator TesttestThatAFailedUploadResultsInAnEventualRetry]` tests
- Fix https://github.com/firebase/firebase-ios-sdk/issues/7780 (URLSession delegate retain cycle)
- fix comment (from #3)
Enabling diagnostics on CI will be implemented in the following PRs, related draft: https://github.com/firebase/firebase-ios-sdk/pull/7778
> Fix diagnostics warnings

- GoogleDataTransport.podspec
- GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer.h
- GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORConsoleLogger.h
- GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCOREventTransformer.h
- GoogleDataTransport/GDTCORTests/Integration/GDTCORIntegrationTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORTransformerTest.m
Fixes [#7177](https://github.com/firebase/firebase-ios-sdk/issues/7177)
> Rename transform: API to transformGDTEvent:

- CHANGELOG.md
- Package.swift
A new `Platform` type: [`macCatalyst`](https://developer.apple.com/documentation/swift_packages/platform/3788284-maccatalyst) was added in Xcode 13 (so I wonder if the GDT catalyst build has been broken since b1?).
The fix here is basically the same as seen in https://github.com/firebase/firebase-ios-sdk/pull/6426 to fix https://github.com/firebase/firebase-ios-sdk/issues/6408.
I extended the `Platform` type to conditionally return a platform that Xcode 13 or Xcode 12 will recognize.
I don't think including `.macOS` in the platforms array seems to matter (concluding from 🟢 `spm` CI). Open to other ideas though.
We could remove this fix when we drop Xcode 12
> Fix Xcode13b4 Catalyst build

- CHANGELOG.md
After merging this, **I'll tag and release 9.1.1 for SPM-only today**. This version patches in #36 
Unblocks https://github.com/firebase/quickstart-ios/pull/1279
> Update CHANGELOG for SPM 9.1.1

- GoogleDataTransport.podspec
Good call @paulb777 !
Bumping the podspec here since we are doing a SPM-only release for 9.1.1. Bumping the podspec now makes it easy to keep the next update in sync between SPM and CP. This podspec will not be published.
> Bump podspec to 9.1.1 (not to be released)

- GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m
Local methods were redeclaring methods from UIApplicationDelegateProtocol.
> Fix up compilation with `-Woverriding-method-mismatch`

- .github/workflows/datatransport.yml
The workflow job was trying to `xcode-select` an Xcode version that no longer exists on the `macOS-latest` image.
Set the workflow job to run on the  `macOS-10.15` image.
Unblocks CI in #46
Related: https://github.com/firebase/firebase-ios-sdk/pull/7101
#no-changelog
> Fix `watchos-testapp` workflow's macOS image

- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCOREventDropReason.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORMetricsControllerProtocol.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetricsController.h
This is the initial commit for the new `metrics-main` branch. It stubs out the base components for metric tracking implementation.
I have a series of small PR's queued up.
> [Metrics] Stub out base components

- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCOREventDropReason.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORMetricsControllerProtocol.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORRegistrar.h
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h
The registration code mirrors that of the other core GDT components (storage and uploader).
Successor PR to first PR: https://github.com/google/GoogleDataTransport/pull/48
> [Metrics] Add plumbing for metrics controller registration

- GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
- GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
- GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTUploadOperation.h
- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORMetricsControllerProtocol.h
The metrics controller will be passed to each upload operation. 
In future PR, the upload operation will use it's retained metrics controller to fetch metrics for adding to upload batch.
> [Metrics] Add plumbing for passing metrics controller to upload operation

- GoogleDataTransport.podspec
- GoogleDataTransport/GDTCORLibrary/GDTCORConsoleLogger.m
- GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORConsoleLogger.h
- Package.swift
- README.md
Here's an example logging output from a simple app with Crashlytics:
```
2022-02-17 12:21:21.382201-0500 CrashlyticsExample[49465:568756] 8.12.1 - [GoogleDataTransport][I-GDT000000] Transport object created. mappingID:1206 transformers:(null) target:1002
2022-02-17 12:21:21.485079-0500 CrashlyticsExample[49465:568750] 8.12.1 - [GoogleDataTransport][I-GDT000000] Event <GDTCOREvent: 0x600003ae48c0> created. ID:0874962B4BFC45BC9DCB4F1113D564AD mappingID: 1206 target:1002
2022-02-17 12:21:21.485241-0500 CrashlyticsExample[49465:568750] 8.12.1 - [GoogleDataTransport][I-GDT000000] Event <GDTCOREvent: 0x600003af8eb0> created. ID:4025D3072A684159B36008155EFB7155 mappingID: 1206 target:1002
2022-02-17 12:21:21.485442-0500 CrashlyticsExample[49465:568750] 8.12.1 - [GoogleDataTransport][I-GDT000000] …
```
> Make GoogleDataTransport use GoogleUtilities logging level

- CHANGELOG.md
- GoogleDataTransport.podspec
- GoogleDataTransport/GDTCCTWatchOSTestApp/Podfile
- Package.swift
See https://github.com/google/nanopb-podspec/pull/19 and https://github.com/firebase/firebase-ios-sdk/pull/9765
> Update to allow update to nanopb 0.3.9.9

- CHANGELOG.md
- GoogleDataTransport.podspec
- GoogleDataTransport/GDTCORLibrary/GDTCORConsoleLogger.m
- GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORConsoleLogger.h
- Package.swift
- README.md
This reverts commit 1a65c30db4fc841e06586441682c2dda036d9db3 and updates the podspec/CHANGELOG for 9.1.4 patch release.
- Changes in #54 cause a deadlock at app startup: https://github.com/firebase/firebase-ios-sdk/pull/9768#issuecomment-1119665363
- See how this branch compares to the commit on `main` before #54 merged: https://github.com/google/GoogleDataTransport/compare/5fe18c35562a2a2c463d69165e20f401d98f25b5...nc/rollback-54
> Rollback #54 and update for 9.1.4 patch release

- GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
- GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
- GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
- GoogleDataTransport/GDTCORLibrary/GDTCOREventMetricsCounter.m
- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage+Promises.m
- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsMetadata.m
- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORMetricsControllerProtocol.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
- GoogleDataTransport/GDTCORLibrary/Private/GDTCOREventMetricsCounter.h
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetricsMetadata.h
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORMetricsControllerFake.h
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORMetricsControllerFake.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORMetricsControllerTest.m
I'm working from a top-down approach to the `GDTCORMetricsController` type. So I'm largely just defining and stubbing out other APIs to get things building.
- Add initial implementation of `GDTCORMetricsController.m` (will be refined in following PR)
- Stub out unit tests for `GDTCORMetricsController.m` (will be completed in following PR, want to keep this PR smaller)
- Added new types like `GDTCORMetricsMetadata` and `GDTCORMetricsCounter` that are used by `GDTCORMetricsController.m`
> [Metrics] Implement metrics controller 

- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORMetricsControllerTest.m
-  Followup to #64 
- Add unit tests for the remaining two metrics controller APIs (completes unit testing for metrics controller)
- Fix some small bugs I found while testing
> [Metrics] Add metrics controller unit tests (2)

- GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORRegistrar.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORMetricsControllerFake.h
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORMetricsControllerFake.m
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORStorageFake.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORRegistrarTest.m
- The metrics controller is supposed to act as a delegate to the storage object. 
- The idea is for the storage object to tell the metrics controller when events are dropped so the metrics controller can then record them as dropped.
- This PR integrates the storage delegate and registers the metrics controller as the storage delegate.
- Also, fixed some related documentation and added unit tests.
> [Metrics] Integrate the storage delegate

- GoogleDataTransport/GDTCORLibrary/GDTCOREventMetricsCounter.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORRegistrar_Private.h
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventMetricsCounterTest.m
- A `GDTCOREventMetricsCounter` instance lives as a property of `GDTCORMetricsMetadata`. Because `GDTCORMetricsMetadata` will be persisted to disk, both types needs to conform to `NSSecureCoding`. This PR implements that for `GDTCOREventMetricsCounter`.
- The API of this model type (`GDTCOREventMetricsCounter`) has a functional style so I added many unit tests to get complete test coverage of the type.
> [Metrics] Implement `NSSecureCoding` and add unit tests for `GDTCOREventMetricsCounter`

- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsMetadata.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORMetricsMetadata.h
- GoogleDataTransport/GDTCORTests/Unit/GDTCORMetricsMetadataTest.m
- Follow-up to #67, implement `NSSecureCoding` for `GDTCORMetricsMetadata` and add unit tests.
- Now that the necessary data models have functioning `NSSecureCoding` implementations, the next PR will implement the storage-level API to read and write metrics metadata.
> [Metrics] Implement `NSSecureCoding` and add unit tests for `GDTCORMetricsMetadata`

- GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage+Promises.m
- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsController.m
- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORPlatform.h
- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORStorageFake.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventMetricsCounterTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORMetricsMetadataTest.m
- I've been working top down and the storage API to fetch and update the metrics metadata is the last component.
- This PR adds a new API to fetch and update metrics metadata using a handler block.
- Added unit tests to validate it's responsibilities.
- Refactored out a decoding function to a new API to separate concerns, improve type safety, and fix subtle bug.
- Implement `- transportBytes` for the `GDTCORMetrics` model object to convert it into a proto.
- Integration and E2E tests
> [Metrics] Implement metrics storage and add unit tests

- GoogleDataTransport/GDTCORLibrary/GDTCOREventMetricsCounter.m
- GoogleDataTransport/GDTCORLibrary/GDTCORMetricsMetadata.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventMetricsCounterTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORMetricsMetadataTest.m
- While I expect it to be _very_ unlikely, I wanted to improve the `NSSecureCoding` conformance to detect and gracefully handle possible data corruption. 
- This helps avoid unexpected `nil`-related exceptions/behavior down the line if corrupted data was decoded into either `GDTCORMetricsMetadata` or `GDTCOREventMetricsCounter`.
- Added respective unit tests to test this behavior.
> [Metrics] Handle potential data corruption when decoding types

- CHANGELOG.md
- GoogleDataTransport.podspec
- Following the merge of `metrics-main` (#77), this PR preps the podspec and CHANGELOG for the 9.2.0 release
> [v9.2.0] Update podspec and CHANGELOG for 9.2.0

- GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageSizeBytes.h
- When building with Xcode, the `uint64_t` type is included in the prelude but that doesn't seem to be the case when building internally in g3. So, adding a `Foundation` import seems like a lightweight fix to keep things consistent.
- The related issue that prompted this PR seems to only affect building in g3.
> [Metrics] Add `Foundation` import to header `GDTCORStorageSizeBytes.h`

- GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
- The flat file storage tests have a helper API to generate events until the storage cache reaches a certain size. Recently, it has become the source of flakes from the storage queue getting backed up enough to prevent the `storeEvent` expectations from getting fulfilled on time. These flakes were hard to reproduce locally and in GHA but were fairly deterministic when building in g3. 
- The fix is to synchronously drain the queue each time an event is stored in the below helper API.
> [Infra] Fix source of flake in test helper

- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
Addresses a TODO I left while working on the metrics feature. Rather than manually declare ivars, explicitly use:
```objc
@synthesize `property` = `_property`
```
#no-changelog
> [Cleanup] Synthesize ivars instead of manual declaration

- .github/workflows/check.yml
- .github/workflows/datatransport.yml
- .github/workflows/spm.yml
- .github/workflows/test_coverage.yml
watchOS does not work with `pod lib lint` and Xcode 14
Also do other CI updates to keep it green.
> Update CI for Xcode 14

- .github/workflows/check.yml
- README.md
- Bump clang-format to v15 because of https://github.com/llvm/llvm-project/issues/49340
- See https://github.com/firebase/firebase-ios-sdk/pull/10451
> [Infra] Bump clang-format to v15

- Gemfile
- Gemfile.lock
Updated to CocoaPods 1.14.0 to match https://github.com/firebase/firebase-ios-sdk/pull/12008.
> Update CocoaPods to v1.14.0

- CHANGELOG.md
- GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
- GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCOREvent.h
- GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORTransport.h
- GoogleDataTransport/GDTCORTests/Unit/GDTCORProductDataTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORTransportTest.m
Clients typically use the `-[GDTCORTransport eventForTransport]` API to create events. This PR adds an additional factory API to create events with given `productData`. This will likely be preferred over using the `GDTCOREvent` initializer because clients may not retain the `mappingID` and `target` in the context where they wish to create an event for transport.
> Add public convenience API for generating a transport event with product data

- GoogleDataTransport.podspec
Enable update to nanopb 2.30910 for privacy manifests
Both this and nanopb are already staged at SpecStaging and being tested in https://github.com/firebase/firebase-ios-sdk/pull/12412
> Enable nanopb privacy manifest update

- CHANGELOG.md
- GoogleDataTransport/GDTCORLibrary/GDTCORLogSourceMetrics.m
`[NSMutableDictionary  dictionaryWithDictionary:nil]` returns an empty dictionary, but the behavior is undocumented and the signature of the API does not indicate that the dictionary parameter may be nil. This leads to the profiler warning in #124
Fix #124
> [NFC] Fix null pointer profiler warning

- .github/workflows/datatransport.yml
CI is consistently failing to build the watchOS test app. 
From https://github.com/google/GoogleDataTransport/actions/runs/9154878993:
❌  error: Watch-Only Application Stubs are not available when building for watchOS Simulator. (in target 'GDTWatchOSTestApp' from project 'GDTWatchOSTestApp')
This was introduced when https://github.com/firebase/firebase-ios-sdk/pull/12966 started specifying the sdk parameter to xcodebuild (which is needed to build pod-lib-lint tests for watchos).
It's not obvious how to correctly update the watchOS app builds here and in messaging.yml, so disabling for now.
> Disable failing watchos test in CI

- CHANGELOG.md
- GoogleDataTransport.podspec
- GoogleDataTransport/GDTCCTLibrary/GDTCCTURLSessionDataResponse.m
- GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
- GoogleDataTransport/GDTCCTLibrary/NSURLSession+GDTCCTPromises.m
- GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTURLSessionDataResponse.h
- GoogleDataTransport/GDTCCTLibrary/Private/NSURLSession+GDTCCTPromises.h
- Package.swift
GDT depended on GoogleUtilities solely to use GoogleUtilities's promise based APIs deleted in https://github.com/google/GoogleUtilities/pull/186
> [v10] Remove GoogleUtilities dependency

- Package.swift
Fix merge conflicts in https://github.com/google/GoogleDataTransport/pull/141 and bump `nanopb` minimum to `2.30910.0` in `Package.swift`.
> [v10] Merge main into release-10.0, bump nanopb to 2.30910.0

- .github/workflows/datatransport.yml
The flagged line in https://github.com/firebase/quickstart-ios/issues/1595 doesn't seem to be a valid issue, but we should still be running static analyzer in CI.
> add analyze to ci

- .github/workflows/check.yml
- GoogleDataTransport/GDTCORLibrary/GDTCORAssert.m
This simplifies things by getting clang-format from the `firebase-ios-sdk` checkout during CI rather than from this repo.
Corresponding GoogleUtils PR: https://github.com/google/GoogleUtilities/pull/218
> [Infra] Prefer `setup_check.sh` over manual config

- README.md
> [Infra] Update README.md code formatting docs
